language: node_js
node_js:
- '8'
install:
- npm i -g metricly-cli
script:
- metricly package validate
notifications:
  slack:
    secure: upAZkyKNhjKzqu43J0ROk7A+fcvPlQnx18NPPTawh3AQ5yHmsMukXosPaSw523tgABGViFwN1335VSOargmZhXBZxnGbyyb6ueraVK4+gDtFz9nHPdU7kDt3E/TRnFF0ZU5euMqggI8ciFE38BRHYED8xdCbguGuo5fGnS2ueFAvskU1UcYDQSo2mN5HLH2zspy9GJucsWVZbufy8EqoDEHSWrgexp6m5oOJMvN/VKLsnKP2K60Y3/XVFzvH3gmiX36zN/u7ru6ArK4JPWYcnYa1UnNGJqXk5BedkrPdImIXCkllKEklqm4tjkWy0cqIufnapQW7PmaR3BPYDusJ8SlopLjdDCgscsOemoFWzRbfIOwO4WcnPRw8FBgDvES0i6gK1mLYXENtuqNcEdiDWFN7fp1OxeBPG6d/ENdlPtxBAKdM1RNUK7RHCN/TdiNkeZfKbVmtgzWJs2JtxCXp7qV7PHz/1S4tZLL+0ttkECghUpcdCpvCtwO8vySYb0gTU0lgoQPOjMzD1R7GLFgx0c0NVhnLeE4WXHp7bpqxV8Xx94x8WpPNVUivhdoW+Ju1kjEUmgx/aUUtCkdT/qFoZY6buhZWiL/AYZaFyMep4eRHDiPHX4zUCBiAtAjAVFNiX6+FXiy6HqunregHAHPrz1SjlqkILAtYuoEeu35XlFQ=
